#pragma once

#define MY_DRIVER_DEVICE 0x8000
#define PROCESS_PERMISSION CTL_CODE(MY_DRIVER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ELEVATE_TOKEN CTL_CODE(MY_DRIVER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)